import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";
import useSWR from "swr";

const inter = Inter({ subsets: ["latin"] });

const getJobListings = (jobListingUrl: string) => {
  const apiUrl = new URL(`${window.location.origin}/api/job-listings`);

  // add query
  apiUrl.searchParams.append("url", jobListingUrl);

  return fetch(apiUrl.toString())
    .then((res) => res.json())
    .then((json) => json.data);
};

export default function Home() {
  const [jobUrl, setJobUrl] = useState("");
  const [jobUrlCopy, setJobUrlCopy] = useState<string | null>(null);

  const swrKey = jobUrlCopy ? ["/api/job-listings", jobUrlCopy] : null;
  const { data, isLoading } = useSWR<any[]>(swrKey, ([_, jobListingUrl]) =>
    getJobListings(jobListingUrl)
  );

  console.log({ data });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input
          placeholder="Lever Job URL"
          value={jobUrl}
          onChange={(e) => setJobUrl(e.target.value)}
        />
        <button
          onClick={() => {
            console.log(jobUrl);

            setJobUrlCopy(jobUrl);
          }}
        >
          Scrape
        </button>

        {isLoading ? (
          <div>loading</div>
        ) : (
          <ul>
            {data &&
              data.map((job) => {
                const categories = job.jobCategories;

                return (
                  <li key={job.id}>
                    <h3>{job.position}</h3>
                    <a href={job.link}>Apply</a>

                    <span>
                      <span>{categories.location}</span> |
                      <span> {categories.department}</span> |
                      <span> {categories.workplaceType}</span>
                    </span>
                  </li>
                );
              })}
          </ul>
        )}
      </main>
    </>
  );
}
